[workspace]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
description = "Redstart: A Lightweight Reusable Booster"
name = "redstart"
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]
version = "2.0.0"

[tasks]
dev = "marimo edit"

[dependencies]
python = "*"
numpy = "*"
scipy = "*"
matplotlib = "*"
ruff = "*"
ipython = ">=9.13.0,<10"

[pypi-dependencies]
marimo = ">=0.20,<0.21"

